### ISSUE TITLE
feature idea -- integrate with google map and distance algorithm

### ISSUE THREAD

**Issue by Pandahisham** [DraperStudio/Laravel-Addressable#3]
thanks for package , most of the time address data is needed to be shown on a map and queried for distance , right now there are two separate packages that can integrated with this to make it a all purpose library , https://github.com/djoudi/Phpgmaps and https://github.com/Pandahisham/geodistance

**Comment by DraperStudio** [comment]
Tagged v1.1.0 which now supports distance search by using https://github.com/jackpopp/geodistance.

```
User::findByDistance(5, 'miles', $lat, $lng); // will return an array with "addressable" models
```
